/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';

export interface AllergyIntoleranceDSTU2Reaction {
  /**
   * Will always be \"confirmed\". All allergies documented within Epic are known allergies and are confirmed.
   */
  certainty?: string;
  manifestation?: Array<CodeableConcept>;
  /**
   * Date allergy was first noticed.
   */
  onset?: string;
  substance?: CodeableConcept;
}
