/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A single instance of a FHIR Binary resource.
 */
export interface BinaryR4 { 
    /**
     * This is always \"application/pdf\" for radiology result data.
     */
    contentType?: string;
    /**
     * The note or document content as a base64-encoded value.
     */
    data?: string;
    /**
     * <p>The Binary FHIR ID.</p>
     */
    id?: string;
}