/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConditionDSTU2 } from './conditionDSTU2';

/**
 * Entry in the bundle.
 */
export interface BundleEntryConditionDSTU2 {
  resource?: ConditionDSTU2;
}
