/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CareTeamR4Participant } from './careTeamR4Participant';
import { CodeableConcept } from './codeableConcept';
import { Extension } from './extension';
import { Period } from './period';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface CareTeamR4 { 
    extension?: Extension;
    category?: CodeableConcept;
    /**
     * CareTeam FHIR ID
     */
    id?: string;
    /**
     * The name of the care team.
     */
    name?: string;
    participant?: CareTeamR4Participant;
    period?: Period;
    /**
     * The status of the episode for which the care team is defined.
     */
    status?: string;
    subject?: Reference;
}