/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CarePlanDSTU2ActivityDetail } from './carePlanDSTU2ActivityDetail';

/**
 * Action to occur as part of the plan.
 */
export interface CarePlanDSTU2Activity { 
    detail?: CarePlanDSTU2ActivityDetail;
}