/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CarePlanR4ActivityDetail } from './carePlanR4ActivityDetail';
import { Reference } from './reference';

/**
 * Actions to occur as part of the care plan.
 */
export interface CarePlanR4Activity { 
    detail: CarePlanR4ActivityDetail;
    reference: Reference;
}