/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reference } from './reference';

/**
 * <p>Message or Attachment (PDF) payload.</p>
 */
export interface CommunicationR4Payload { 
    contentReference?: Reference;
    /**
     * <p>Contains the content. Append all payload.contentString elements together to form the entire message body.</p>
     */
    contentString?: string;
}