/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Extension } from './extension';

/**
 * The policy of the consent document.
 */
export interface ConsentR4Policy { 
    extension?: Extension;
    /**
     * Always set to \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\".
     */
    uri?: string;
}