/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { ConsentSTU3Meta } from './consentSTU3Meta';
import { ConsentSTU3Policy } from './consentSTU3Policy';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { Reference } from './reference';

/**
 * An instance of the R4 Consent resource.
 */
export interface ConsentSTU3 { 
    category?: CodeableConcept;
    extension: Extension;
    consentingParty: Reference;
    /**
     * Date and time that the consent document was created.
     */
    dateTime?: string;
    /**
     * The Consent FHIR ID.
     */
    id?: string;
    identifier?: Identifier;
    meta: ConsentSTU3Meta;
    patient?: Reference;
    policy?: ConsentSTU3Policy;
    /**
     * <p>The state of the consent. This value follows the specification of the FHIR ConsentState value set. The following values have default out-of-the-box support in Epic. Additional statuses can be mapped by Epic organizations if desired.</p> <ul> <li>draft</li> <ul> <li>Corresponds to Epic value 11-Not Received</li> </ul> <li>active</li> <ul> <li>Corresponds to Epic values 10-Received and 20-Accepted</li> </ul> <li>rejected</li> <ul> <li>Corresponds to Epic value 1-Unknown</li> </ul> <li>entered-in-error</li> <ul> <li>Corresponds to Epic value 35-Error</li> </ul> <li>inactive</li> <ul> <li>Does not correspond to any Epic value by default</li> </ul> <li>proposed</li> <ul> <li>Does not correspond to any Epic value by default</li> </ul> </ul>
     */
    status?: string;
}