/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { CoverageSTU3Meta } from './coverageSTU3Meta';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { Period } from './period';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface CoverageSTU3 { 
    beneficiary?: Reference;
    extension: Extension;
    /**
     * The dependent.
     */
    dependent?: string;
    identifier?: Identifier;
    meta: CoverageSTU3Meta;
    payor?: Reference;
    period?: Period;
    relationship?: CodeableConcept;
    /**
     * <p>Financial Resource Status Code. The following values are supported:</p> <ul>   <li>active</li>   <li>cancelled</li>   <li>draft</li> </ul>
     */
    status?: string;
    subscriber?: Reference;
    /**
     * Subscriber ID
     */
    subscriberId?: string;
}