/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { DeviceR4DeviceName } from './deviceR4DeviceName';
import { DeviceR4Specialization } from './deviceR4Specialization';
import { DeviceR4UdiCarrier } from './deviceR4UdiCarrier';
import { DeviceR4Version } from './deviceR4Version';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface DeviceR4 { 
    /**
     * Area code and phone number.
     */
    contact: any;
    deviceName: DeviceR4DeviceName;
    /**
     * Distinct identification code.
     */
    distinctIdentifier: string;
    /**
     * <p>Device expiration date.</p>
     */
    expirationDate: string;
    location: Reference;
    /**
     * <p>Device lot number.</p>
     */
    lotNumber: string;
    /**
     * <p>Date of device manufacture.</p>
     */
    manufactureDate: string;
    /**
     * <p>Device manufacturer.</p>
     */
    manufacturer: string;
    /**
     * <p>Device model number.</p>
     */
    modelNumber: string;
    note: Annotation;
    owner: Reference;
    parent: Reference;
    patient: Reference;
    /**
     * Implant type information, including: <ul><li>Permanence <li>Radioactive <li>Site <li>Laterality <li>Size <li>GUDID request status <li>GUDID MRI safety information <li>GUDID contains dry or latex rubber <li>GMDN Preferred term name</ul>
     */
    property: any;
    safety: CodeableConcept;
    /**
     * <p>Device serial number.</p>
     */
    serialNumber: string;
    specialization?: DeviceR4Specialization;
    /**
     * <p>One of the following values:</p> <ul>   <li>active</li>   <li>inactive</li>   <li>entered-in-error</li>   <li>unknown</li> </ul>
     */
    status: string;
    type: CodeableConcept;
    udiCarrier: DeviceR4UdiCarrier;
    version?: DeviceR4Version;
}