/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <p>Device name and type details.</p>
 */
export interface DeviceR4DeviceName { 
    /**
     * <p>The name of the device.</p>
     */
    name?: string;
    /**
     * <p>Always set to \"other\".</p>
     */
    type?: string;
}