/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { DocumentReferenceDSTU2Content } from './documentReferenceDSTU2Content';
import { DocumentReferenceDSTU2Context } from './documentReferenceDSTU2Context';
import { Identifier } from './identifier';
import { Reference } from './reference';

/**
 * An instance of the DSTU2 DocumentReference resource.
 */
export interface DocumentReferenceDSTU2 {
  _class?: CodeableConcept;
  /**
   * The document referenced.
   */
  content?: Array<DocumentReferenceDSTU2Content>;
  context?: DocumentReferenceDSTU2Context;
  /**
   * Document creation time.  This element is not populated in February 2019 and later versions of Epic. In February 2019 and later, use the Indexed element instead.
   */
  created?: string;
  /**
   * The DocumentReference FHIR ID.
   */
  id?: string;
  /**
   * When this document reference was created.
   */
  indexed?: string;
  masterIdentifier?: Identifier;
  /**
   * Current, superseded, or entered-in-error.
   */
  status?: string;
  subject?: Reference;
  type?: CodeableConcept;
}
