/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Where to access the document.
 */
export interface DocumentReferenceDSTU2ContentAttachment { 
    /**
     * Media type of the resource.
     */
    contentType?: string;
    /**
     * A reference to the Binary resource which contains the document content.
     */
    url?: string;
}