/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { ExplanationOfBenefitR4CareTeam } from './explanationOfBenefitR4CareTeam';
import { ExplanationOfBenefitR4Diagnosis } from './explanationOfBenefitR4Diagnosis';
import { ExplanationOfBenefitR4Insurance } from './explanationOfBenefitR4Insurance';
import { ExplanationOfBenefitR4Item } from './explanationOfBenefitR4Item';
import { ExplanationOfBenefitR4Procedure } from './explanationOfBenefitR4Procedure';
import { ExplanationOfBenefitR4SupportingInfo } from './explanationOfBenefitR4SupportingInfo';
import { Identifier } from './identifier';
import { Period } from './period';
import { Reference } from './reference';

/**
 * An instance of the R4 ExplanationOfBenefit resource.
 */
export interface ExplanationOfBenefitR4 {
  billablePeriod?: Period;
  /**
   * The members of the team who provided the products and services.
   */
  careTeam?: Array<ExplanationOfBenefitR4CareTeam>;
  /**
   * Date when the claim was created.
   */
  created?: string;
  /**
   * Each diagnosis on the claim will have an entry. Rx claims do not support diagnosis.
   */
  diagnosis?: Array<ExplanationOfBenefitR4Diagnosis>;
  /**
   * Description of the status of the adjudication.
   */
  disposition?: string;
  facility?: Reference;
  /**
   * The FHIR ID.
   */
  id?: string;
  identifier?: Array<Identifier>;
  /**
   * Member's ID from the coverage.
   */
  insurance?: Array<ExplanationOfBenefitR4Insurance>;
  insurer?: Reference;
  /**
   * Service lines.
   */
  item?: Array<ExplanationOfBenefitR4Item>;
  /**
   * Non-AP Claims: complete Paid AP claims: complete Claim in the status of \"new\": queued (this status is very rare) All other claims: partial
   */
  outcome?: string;
  patient?: Reference;
  /**
   * ICD procedures.
   */
  procedure?: Array<ExplanationOfBenefitR4Procedure>;
  provider?: Reference;
  /**
   * Status of the claim. 'active' and 'cancelled' claims can be shown in search requests.
   */
  status?: string;
  subType?: CodeableConcept;
  /**
   * The following supporting info is supported: All claims: Received date All Medical claims: Discharge disposition Occurrence span codes Admission type Admission source UB claims: Type of Bill Rx Claims: Record status code Reject Override Code Reject code Fill Number Days Supply DAW Code
   */
  supportingInfo?: Array<ExplanationOfBenefitR4SupportingInfo>;
  type?: CodeableConcept;
}
