/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Reference } from './reference';

/**
 * A single Goal resource.
 */
export interface GoalSTU3 {
  addresses: Array<Reference>;
  category: Array<CodeableConcept>;
  description?: CodeableConcept;
  expressedBy: Reference;
  /**
   * The Goal FHIR ID.
   */
  id?: string;
  note: Array<Annotation>;
  /**
   * When pursuit of the goal begins.
   */
  startDate: string;
  /**
   * <p>The current status of the goal. The following values are supported:</p> <ul> <li>in-progress</li> <li>achieved</li> <li>cancelled</li> </ul>  <p>The status for received document records is always \"in-progress.\"</p>
   */
  status?: string;
  subject: Reference;
}
