/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Identifier } from './identifier';
import { ImmunizationDSTU2DoseQuantity } from './immunizationDSTU2DoseQuantity';
import { ImmunizationR4Performer } from './immunizationR4Performer';
import { Reference } from './reference';

/**
 * A single Immunization resource.
 */
export interface ImmunizationR4 { 
    doseQuantity: ImmunizationDSTU2DoseQuantity;
    encounter: Reference;
    /**
     * Vaccine expiration date.
     */
    expirationDate: string;
    /**
     * The Immunization FHIR ID.
     */
    id?: string;
    identifier: Identifier;
    /**
     * Indicates that the dose wasn’t full strength. Replaces the extension \"isSubpotent\" in STU3.
     */
    isSubpotent: boolean;
    location: Reference;
    /**
     * Vaccine lot number.
     */
    lotNumber: string;
    manufacturer: Reference;
    note: Annotation;
    /**
     * Vaccination administration date and time (if available). Previously \"date\" in STU3 and earlier.
     */
    occurrenceDateTime: string;
    patient?: Reference;
    performer: ImmunizationR4Performer;
    /**
     * Whether the immunization data is historical and therefore reported by a patient or another system. If historical, \"false\" is returned as this system is not the primary source of the data. 
     */
    primarySource: boolean;
    reportOrigin: CodeableConcept;
    route: CodeableConcept;
    site: CodeableConcept;
    /**
     * <p>Status of the Immunization. Possible values are:</p> <ul> <li>completed</li> <li>entered-in-error</li> <li>not-done</li> </ul> <p>*Note: incomplete Immunizations are not returned.</p>
     */
    status?: string;
    statusReason: CodeableConcept;
    vaccineCode?: CodeableConcept;
}