/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { ImmunizationRecommendationR4DateCriterion } from './immunizationRecommendationR4DateCriterion';

export interface ImmunizationRecommendationR4Recommendation {
  /**
   * The date when the recommended immunization is considered due or overdue.
   */
  dateCriterion?: Array<ImmunizationRecommendationR4DateCriterion>;
  forecastStatus?: CodeableConcept;
  vaccineCode?: Array<CodeableConcept>;
}
