/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Identifier } from './identifier';
import { ImmunizationDSTU2DoseQuantity } from './immunizationDSTU2DoseQuantity';
import { ImmunizationDSTU2Explanation } from './immunizationDSTU2Explanation';
import { Reference } from './reference';

/**
 * A single Immunization FHIR resource.
 */
export interface ImmunizationDSTU2 {
  /**
   * Vaccination administration date.
   */
  date: string;
  doseQuantity: ImmunizationDSTU2DoseQuantity;
  /**
   * Vaccine expiration date.
   */
  expirationDate: string;
  explanation: ImmunizationDSTU2Explanation;
  /**
   * Immunization FHIR ID.
   */
  id?: string;
  identifier: Array<Identifier>;
  /**
   * Vaccine lot number.
   */
  lotNumber: string;
  manufacturer: Reference;
  note: Array<Annotation>;
  patient?: Reference;
  performer: Reference;
  /**
   * Indicates a self-reported record.
   */
  reported: boolean;
  requester: Reference;
  route: CodeableConcept;
  site: CodeableConcept;
  /**
   * <p>Status of the Immunization. Possible values are:</p> <ul> <li>completed</li> <li>entered-in-error</li> <li>in-progress</li> <li>on-hold</li> </ul>
   */
  status?: string;
  vaccineCode?: CodeableConcept;
  /**
   * Flag for whether the immunization was given.
   */
  wasNotGiven?: boolean;
}
