/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { ListR4Entry } from './listR4Entry';

/**
 * An instance of the STU3 List resource
 */
export interface ListSTU3 {
  code?: CodeableConcept;
  /**
   * When the list was prepared.
   */
  date?: string;
  emptyReason?: CodeableConcept;
  /**
   * Array of responses.
   */
  entry?: Array<ListR4Entry>;
  /**
   * The processing mode that applies to this list. Always \"snapshot\".  Values can be found <a href=\"https://www.hl7.org/fhir/valueset-list-mode.html\">here</a>.
   */
  mode?: string;
  /**
   * Status of the patient list. Always \"current\".  Values can be found <a href=\"https://www.hl7.org/fhir/valueset-list-status.html\">here</a>.
   */
  status?: string;
  /**
   * The descriptive name for the list.
   */
  title?: string;
}
