/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { ListR4Entry } from './listR4Entry';
import { Reference } from './reference';

/**
 * An instance of the R4 List FHIR resource.
 */
export interface ListR4 { 
    code?: CodeableConcept;
    emptyReason: CodeableConcept;
    entry?: ListR4Entry;
    /**
     * The encoded list ID.
     */
    id?: string;
    /**
     * The processing mode that applies to this list. Always \"working\".
     */
    mode?: string;
    /**
     * Status of the problem list. Always \"current\" because each list represents only the patient’s current problems.  
     */
    status?: string;
    subject?: Reference;
    /**
     * The title representing this entity. Always “Problem List”.
     */
    title?: string;
}