/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The amount of therapeutic or other substance given at one administration event.
 */
export interface MedicationOrderDSTU2DosageInstructionDoseQuantity { 
    /**
     * A computer processable form of the units in some unit representation system.
     */
    code?: string;
    /**
     * How the value should be understood and represented - whether the actual value is greater or less than the stated value due to measurement issues. E.g. if the comparator is \"<\" , then the real value is < stated value.
     */
    comparator?: string;
    /**
     * The identification of the system that provides the coded form of the unit.
     */
    system?: string;
    /**
     * A human-readable form of the units.
     */
    unit?: string;
    /**
     * The value of the measured amount. The value includes an implicit precision in the presentation of the value.
     */
    value: any;
}