/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A Response Type
 */
export interface MedicationRequestSTU3Substitution {
  /**
   * <p>If the Dispense as Written item is set to 1, we return this as No.</p> <p>If Dispense as Written does not equal 1, we don't return a substitution element.</p>
   */
  allowed: boolean;
}
