/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Period } from './period';

/**
 * Repeat occurrence information.
 */
export interface MedicationRequestR4TimingRepeat {
  boundsPeriod: Period;
  /**
   * If the medication is not PRN, and CountType is Doses, this element is populated with the count value.
   */
  count: any;
  /**
   * If the medication is PRN, this element is set to Count.
   */
  countMax: any;
  /**
   * The day of the week.
   */
  dayOfWeek: string;
  /**
   * The medication duration. If duration is expressed as a range, this element is populated with the minimum duration.
   */
  duration: any;
  /**
   * If duration is expressed as a range, this element is populated with the maximum duration.
   */
  durationMax: any;
  /**
   * The duration unit.
   */
  durationUnit?: string;
  /**
   * The frequency.
   */
  frequency: any;
  /**
   * The period.
   */
  period: any;
  /**
   * The period unit.
   */
  periodUnit: string;
  /**
   * The time of day.
   */
  timeOfDay: string;
  /**
   * The administration timing.
   */
  when: string;
}
