/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { MedicationStatementSTU3Dosage } from './medicationStatementSTU3Dosage';
import { MedicationStatementSTU3Meta } from './medicationStatementSTU3Meta';
import { Period } from './period';
import { Reference } from './reference';

/**
 * An instance of the STU3 MedicationStatement resource.
 */
export interface MedicationStatementSTU3 { 
    extension: Extension;
    basedOn?: Reference;
    category?: CodeableConcept;
    /**
     * The date the prescription was written.
     */
    dateAsserted?: string;
    dosage?: MedicationStatementSTU3Dosage;
    effectivePeriod?: Period;
    identifier?: Identifier;
    informationSource?: Reference;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference;
    meta: MedicationStatementSTU3Meta;
    note?: Annotation;
    /**
     * The order status of the medication.
     */
    status?: string;
    subject?: Reference;
    /**
     * This element is set to \"unk\" for unknown.
     */
    taken?: string;
}