/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { MedicationRequestSTU3DosageInstruction } from './medicationRequestSTU3DosageInstruction';
import { MedicationRequestSTU3Requester } from './medicationRequestSTU3Requester';
import { MedicationRequestSTU3Substitution } from './medicationRequestSTU3Substitution';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface MedicationRequestSTU3 {
  /**
   * The date the prescription was written.
   */
  authoredOn?: string;
  category?: CodeableConcept;
  /**
   * Contains resources referenced from the supportingInformation element. Currently, body weight and height Observations are supported (LOINC 8302-2 for height and LOINC 29463-7 for weight).
   */
  contained?: Array<any>;
  /**
   * Medication supply authorization.
   */
  dispenseRequest?: any;
  /**
   * A Response Type
   */
  dosageInstruction?: Array<MedicationRequestSTU3DosageInstruction>;
  groupIdentifier?: Identifier;
  identifier?: Array<Identifier>;
  /**
   * Hardcoded to \"order\".
   */
  intent?: string;
  medicationCodeableConcept?: CodeableConcept;
  medicationReference?: Reference;
  note?: Array<Annotation>;
  extension?: Array<Extension>;
  priorPrescription?: Reference;
  recorder?: Reference;
  requester?: MedicationRequestSTU3Requester;
  /**
   * The status of the medication request.
   */
  status?: string;
  modifierExtension?: Array<Extension>;
  subject?: Reference;
  substitution?: MedicationRequestSTU3Substitution;
  supportingInformation?: Array<Reference>;
}
