/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { MedicationOrderDSTU2DoseQuantity } from './medicationOrderDSTU2DoseQuantity';
import { MedicationOrderDSTU2DoseRange } from './medicationOrderDSTU2DoseRange';
import { MedicationOrderDSTU2Timing } from './medicationOrderDSTU2Timing';

export interface MedicationOrderDSTU2DosageInstruction {
  /**
   * If set to true, indicates that the medication is only taken when needed within the specified schedule rather than at every scheduled dose.
   */
  asNeededBoolean?: boolean;
  doseQuantity?: MedicationOrderDSTU2DoseQuantity;
  doseRange?: MedicationOrderDSTU2DoseRange;
  method?: CodeableConcept;
  route?: CodeableConcept;
  /**
   * Free text dosage instructions can be used for cases where the instructions are too complex to code. When coded instructions are present, the free text instructions may still be present for display to humans taking or administering the medication.
   */
  text?: string;
  timing?: MedicationOrderDSTU2Timing;
}
