/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { MedicationStatementSTU3Timing } from './medicationStatementSTU3Timing';

export interface MedicationStatementSTU3Dosage {
  additionalInstruction?: Array<CodeableConcept>;
  /**
   * True if taken as needed (PRN). False otherwise.
   */
  asNeededBoolean?: boolean;
  /**
   * Amount of medication per dose. The amount of therapeutic or other substance given at one administration event.
   */
  doseQuantity?: any;
  method?: CodeableConcept;
  /**
   * <p>The patient instructions for the prescription.</p> <p>Starting in February 2022 and in November 2021 by special update, the patient-reported sig is returned as well.</p>
   */
  patientInstruction?: string;
  /**
   * <p>Amount of medication per unit of time. Used when the rate is a discrete value.</p> <p>Available starting in February 2022 and in November 2021 by special update.</p>
   */
  rateQuantity?: any;
  /**
   * <p>Amount of medication per unit of time. Used when the rate is a range.</p> <p>Available starting in February 2022 and in November 2021 by special update.</p>
   */
  rateRange?: any;
  route?: CodeableConcept;
  /**
   * The patient instructions for the prescription.
   */
  text?: string;
  timing?: MedicationStatementSTU3Timing;
}
