/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Period } from './period';

/**
 * Medication supply authorization.
 */
export interface MedicationRequestR4DispenseRequest { 
    /**
     * The duration.
     */
    expectedSupplyDuration: any;
    /**
     * The number of discrete refills for the medication.
     */
    numberOfRepeatsAllowed: any;
    /**
     * The quantity.
     */
    quantity: any;
    validityPeriod: Period;
}