/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MedicationDispenseR4DoseAndRate {
  /**
   * Amount of medication per dose. The amount of therapeutic or other substance given at one administration event.
   */
  doseQuantity?: any;
  /**
   * Parses the upper and lower bounds of the dose from above.
   */
  doseRange?: any;
  /**
   * The discrete value of a medication’s rate of infusion.
   */
  rateQuantity?: any;
  /**
   * The high and low values of a medication’s rate of infusion.
   */
  rateRange?: any;
}
