/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The document metadata.
 */
export interface ObservationSTU3Meta {
  /**
   * Available in Netherlands environments only. This element shows that this API conforms to the profile connected to one of the following canonical urls: • http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure • http://nictiz.nl/fhir/StructureDefinition/zib-BodyWeight • http://nictiz.nl/fhir/StructureDefinition/zib-BodyHeight
   */
  profile: string;
}
