/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CodeableConcept } from './codeableConcept';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { OrganizationSTU3Meta } from './organizationSTU3Meta';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface OrganizationSTU3 { 
    /**
     * <p>Whether the organization's record is in active use.</p>
     */
    active: boolean;
    address: Address;
    extension: Extension;
    /**
     * <p>The Organization FHIR ID.</p>
     */
    id?: string;
    identifier: Identifier;
    meta: OrganizationSTU3Meta;
    /**
     * <p>The name used for the organization.</p>
     */
    name: string;
    partOf: Reference;
    /**
     * <p>The phone number, fax number, and emergency phone number.</p>
     */
    telecom: any;
    type: CodeableConcept;
}