/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Identifier } from './identifier';
import { ProcedureRequestSTU3Meta } from './procedureRequestSTU3Meta';
import { ProcedureRequestSTU3Requester } from './procedureRequestSTU3Requester';
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface ProcedureRequestSTU3 {
  /**
   * If set to true, indicates that the order is only performed when needed within the specified schedule.
   */
  asNeededBoolean: boolean;
  /**
   * The order instant. This is the date and time when the status is not draft or unknown.
   */
  authoredOn?: string;
  basedOn?: Array<Reference>;
  code?: CodeableConcept;
  context?: Reference;
  /**
   * This is set to true if the status is draft, cancelled, or unknown.
   */
  doNotPerform: boolean;
  /**
   * FHIR ProcedureRequest ID.
   */
  id?: string;
  identifier?: Array<Identifier>;
  /**
   * The intent code. The full list of potential values can be found <a href'\"http://hl7.org/fhir/stu3/valueset-request-intent.html\">here</a>.
   */
  intent?: string;
  meta: ProcedureRequestSTU3Meta;
  note?: Array<Annotation>;
  /**
   * This event element is populated for auto-released orders.
   */
  occurrenceTiming?: any;
  /**
   * The priority. The full list of potential values can be found <a href=\"http://hl7.org/fhir/stu3/valueset-request-priority.html\">here</a>.
   */
  priority?: string;
  reasonCode?: Array<CodeableConcept>;
  requester?: ProcedureRequestSTU3Requester;
  /**
   * The status code. The full list of potential values can be found <a href=\"http://hl7.org/fhir/stu3/valueset-request-status.html\">here</a>.
   */
  status?: string;
  subject?: Reference;
}
