/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionnaireResponseR4ItemAnswer } from './questionnaireResponseR4ItemAnswer';

/**
 * <p>Answers to the questions in the questionnaire.</p>
 */
export interface QuestionnaireResponseR4Item { 
    answer: QuestionnaireResponseR4ItemAnswer;
    /**
     * This property lists the questionnaire ID, the question ID, along with the DAT of the question as a dot-delimited (.) string.
     */
    linkId?: string;
    /**
     * The prompt of the question or question group.
     */
    text: string;
}