/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface QuestionnaireResponseR4Answer {
  /**
   * The attachment as a binary resource URL.
   */
  valueAttachment?: any;
  /**
   * Boolean value
   */
  valueBoolean?: boolean;
  /**
   * Coding value.
   */
  valueCoding?: any;
  /**
   * Date value
   */
  valueDate?: string;
  /**
   * Decimal value
   */
  valueDecimal?: any;
  /**
   * Quantity value.
   */
  valueQuantity?: any;
  /**
   * String value
   */
  valueString?: string;
  /**
   * Time value
   */
  valueTime?: string;
}
