/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { QuestionnaireResponseR4Item } from './questionnaireResponseR4Item';
import { Reference } from './reference';

/**
 * An instance of the R4 QuestionnaireResponse FHIR resource.
 */
export interface QuestionnaireResponseR4 { 
    /**
     * <p>Date and time the answers were gathered (in UTC). The default is the current time.</p>
     */
    authored: string;
    encounter: Reference;
    /**
     * Identifier for this QuestionnaireResponse resource.
     */
    id?: string;
    identifier?: Identifier;
    item: QuestionnaireResponseR4Item;
    /**
     * Language the questionnaire was answered in. For questionnaire response records that do not list the submission language, no language code is returned. 
     */
    language: string;
    /**
     * <p>The FHIR questionnaire.</p>
     */
    questionnaire: string;
    source: Reference;
    /**
     * <p>Set to In-progress, unless all questionnaires are answered. If all questionnaires are answered, set to Completed.</p>
     */
    status?: string;
    subject: Reference;
}