/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <p>The answer submitted for the question.</p> <p>Single-valued answer to the question. Depending on the type of question, the value sent will be one of the following types:</p> <ul>   <li>valueBoolean</li>   <li>valueDecimal</li>   <li>valueCoding</li>   <li>valueDate</li>   <li>valueTime</li>   <li>valueString</li>   <li>valueQuantity</li>   <li>valueAttachment</li> </ul>
 */
export interface QuestionnaireResponseR4ItemAnswer { 
    /**
     * The attachment as a binary resource URL.
     */
    valueAttachment: any;
    /**
     * Boolean value
     */
    valueBoolean: boolean;
    /**
     * Coding value.
     */
    valueCoding: any;
    /**
     * Date value
     */
    valueDate: string;
    /**
     * Decimal value
     */
    valueDecimal: any;
    /**
     * Quantity value.
     */
    valueQuantity: any;
    /**
     * String value
     */
    valueString: string;
    /**
     * Time value
     */
    valueTime: string;
}