/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reference } from './reference';

/**
 * A Response Type
 */
export interface RelatedPersonR4 {
  /**
   * <p>The name of the RelatedPerson.</p>
   */
  name: Array<any>;
  patient?: Reference;
}
