/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reference } from './reference';
import { RequestGroupR4Action } from './requestGroupR4Action';

/**
 * An instance of the R4 RequestGroup FHIR resource.
 */
export interface RequestGroupR4 { 
    action: RequestGroupR4Action;
    basedOn: Reference;
    /**
     * For oncology RequestGroup, this always equals \"plan\".
     */
    intent?: string;
    /**
     * Plan/cycle status value. Supported values include: <ul> <li>Planned</li> <li>Scheduled</li> <li>Completed</li> <li>Deleted</li> <li>Started</li> <li>Canceled</li> <li>Given Externally</li> <li>Unscheduled</li> <li>Non-Treatment Orders</li> </ul>
     */
    status?: string;
    subject: Reference;
}