/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { Reference } from './reference';
import { ResearchStudyR4Arm } from './researchStudyR4Arm';

/**
 * A Response Type
 */
export interface ResearchStudyR4 { 
    arm: ResearchStudyR4Arm;
    /**
     * <p>Available starting in the August 2021 Epic version. <p>What this study is doing. 
     */
    description: string;
    /**
     * The ResearchStudy FHIR ID.
     */
    id?: string;
    identifier: Identifier;
    principalInvestigator: Reference;
    /**
     * The current state of the study.
     */
    status?: string;
    /**
     * The name of the study.
     */
    title: string;
}