/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { CodeableConcept } from './codeableConcept';
import { Identifier } from './identifier';
import { Reference } from './reference';
import { SpecimenR4Collection } from './specimenR4Collection';

/**
 * A single Specimen resource.
 */
export interface SpecimenR4 { 
    accessionIdentifier: Identifier;
    collection: SpecimenR4Collection;
    /**
     * The Specimen FHIR ID.
     */
    id?: string;
    identifier: Identifier;
    note: Annotation;
    /**
     * The time when the specimen was received for processing. Available starting in November 2021 version of Epic.
     */
    receivedTime: string;
    subject?: Reference;
    type: CodeableConcept;
}