/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Array of codes in the ValueSet.
 */
export interface ValueSetR4ExpansionContains { 
    /**
     * Code value.
     */
    code?: string;
    /**
     * User display value associated with the code.
     */
    display: string;
    /**
     * System value for the code.
     */
    system: string;
}