/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ValueSetR4Expansion } from './valueSetR4Expansion';

/**
 * A single ValueSet resource.
 */
export interface ValueSetR4 { 
    expansion: ValueSetR4Expansion;
    /**
     * The ValueSet FHIR ID.
     */
    id?: string;
    /**
     * Status of the ValueSet. Always \"active\".
     */
    status?: string;
}