/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { BundleQuestionnaireR4 } from '../model/bundleQuestionnaireR4';
import { BundleQuestionnaireResponseR4 } from '../model/bundleQuestionnaireResponseR4';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class SearchPatientEnteredQuestionnairesR4Service {
  protected basePath = 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   *
   *
   * @param patient FHIR Patient ID. All patient-entered questionnaire responses from the specified patient will be returned. Multiple patients cannot be referenced in the search request.
   * @param encounter FHIR Encounter IDs. If provided, the search returns only those patient-entered questionnaire responses associated with the specified encounter(s).
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public questionnaireResponseSearchPatientEnteredQuestionnairesR4(
    patient: string,
    encounter?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<BundleQuestionnaireResponseR4>;
  public questionnaireResponseSearchPatientEnteredQuestionnairesR4(
    patient: string,
    encounter?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<BundleQuestionnaireResponseR4>>;
  public questionnaireResponseSearchPatientEnteredQuestionnairesR4(
    patient: string,
    encounter?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<BundleQuestionnaireResponseR4>>;
  public questionnaireResponseSearchPatientEnteredQuestionnairesR4(
    patient: string,
    encounter?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (patient === null || patient === undefined) {
      throw new Error(
        'Required parameter patient was null or undefined when calling questionnaireResponseSearchPatientEnteredQuestionnairesR4.'
      );
    }

    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec(),
    });
    if (encounter !== undefined && encounter !== null) {
      queryParameters = queryParameters.set('encounter', <any>encounter);
    }
    if (patient !== undefined && patient !== null) {
      queryParameters = queryParameters.set('patient', <any>patient);
    }

    let headers = this.defaultHeaders;

    // authentication (bearer_auth) required
    if (
      this.configuration.apiKeys &&
      this.configuration.apiKeys['Authorization']
    ) {
      headers = headers.set(
        'Authorization',
        this.configuration.apiKeys['Authorization']
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<BundleQuestionnaireResponseR4>(
      'get',
      `${this.basePath}/R4/QuestionnaireResponse`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public questionnaireSearchPatientEnteredQuestionnairesR4(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<BundleQuestionnaireR4>;
  public questionnaireSearchPatientEnteredQuestionnairesR4(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<BundleQuestionnaireR4>>;
  public questionnaireSearchPatientEnteredQuestionnairesR4(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<BundleQuestionnaireR4>>;
  public questionnaireSearchPatientEnteredQuestionnairesR4(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearer_auth) required
    if (
      this.configuration.apiKeys &&
      this.configuration.apiKeys['Authorization']
    ) {
      headers = headers.set(
        'Authorization',
        this.configuration.apiKeys['Authorization']
      );
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<BundleQuestionnaireR4>(
      'get',
      `${this.basePath}/R4/Questionnaire`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
