/**
 * Epic on Fhir
 * All of the components of the Change Healthcare Interoperability Apis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bmain@lumeris.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BundleServiceRequestR4 } from '../model/bundleServiceRequestR4';
import { ServiceRequestR4 } from '../model/serviceRequestR4';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ServiceRequestService {

    protected basePath = 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param ID FHIR ServiceRequest ID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public serviceRequestReadReferralR4(ID: string, observe?: 'body', reportProgress?: boolean): Observable<ServiceRequestR4>;
    public serviceRequestReadReferralR4(ID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServiceRequestR4>>;
    public serviceRequestReadReferralR4(ID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServiceRequestR4>>;
    public serviceRequestReadReferralR4(ID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (ID === null || ID === undefined) {
            throw new Error('Required parameter ID was null or undefined when calling serviceRequestReadReferralR4.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer_auth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ServiceRequestR4>('get',`${this.basePath}/R4/ServiceRequest/${encodeURIComponent(String(ID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param category &lt;p&gt;Set category to the following token construction: system | code, where:&lt;/p&gt; &lt;ul&gt; &lt;li&gt;system: “http://snomed.info/sct”&lt;/li&gt; &lt;li&gt;code: “307835004”&lt;/li&gt; &lt;/ul&gt; &lt;p&gt;The code SCTID: 307835004 represents the  ‘Referral by service’, in order to find CRRN type of ServiceRequests. Either the patient, subject, or encounter must be provided.&lt;/p&gt; 
     * @param encounter Reference to an Encounter resource the procedure request is in.
     * @param onlyscannable If “true”,  only scannable orders and procedures are returned in the response. This feature requires a user to have login department context as part of the API request, otherwise error code 59100 is returned.
     * @param patient Reference to a patient resource for which the request is ordered.
     * @param requester Reference to a practitioner resource who is the authorizing provider for the procedure request.
     * @param status &lt;p&gt;The status of the request. Supported values include:&lt;/p&gt; &lt;ul&gt; &lt;li&gt;draft&lt;/li&gt; &lt;li&gt;active&lt;/li&gt; &lt;li&gt;completed&lt;/li&gt; &lt;li&gt;revoked&lt;/li&gt; &lt;li&gt; unknown&lt;/li&gt; &lt;/ul&gt; &lt;p&gt;This service returns all statuses if this element is not specified.&lt;/p&gt;
     * @param subject Reference to a patient resource for which the request is ordered.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public serviceRequestSearchOrdersR4(category: string, encounter?: string, onlyscannable?: string, patient?: string, requester?: string, status?: string, subject?: string, observe?: 'body', reportProgress?: boolean): Observable<BundleServiceRequestR4>;
    public serviceRequestSearchOrdersR4(category: string, encounter?: string, onlyscannable?: string, patient?: string, requester?: string, status?: string, subject?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BundleServiceRequestR4>>;
    public serviceRequestSearchOrdersR4(category: string, encounter?: string, onlyscannable?: string, patient?: string, requester?: string, status?: string, subject?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BundleServiceRequestR4>>;
    public serviceRequestSearchOrdersR4(category: string, encounter?: string, onlyscannable?: string, patient?: string, requester?: string, status?: string, subject?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling serviceRequestSearchOrdersR4.');
        }







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (category !== undefined && category !== null) {
            queryParameters = queryParameters.set('category', <any>category);
        }
        if (encounter !== undefined && encounter !== null) {
            queryParameters = queryParameters.set('encounter', <any>encounter);
        }
        if (onlyscannable !== undefined && onlyscannable !== null) {
            queryParameters = queryParameters.set('onlyscannable', <any>onlyscannable);
        }
        if (patient !== undefined && patient !== null) {
            queryParameters = queryParameters.set('patient', <any>patient);
        }
        if (requester !== undefined && requester !== null) {
            queryParameters = queryParameters.set('requester', <any>requester);
        }
        if (status !== undefined && status !== null) {
            queryParameters = queryParameters.set('status', <any>status);
        }
        if (subject !== undefined && subject !== null) {
            queryParameters = queryParameters.set('subject', <any>subject);
        }

        let headers = this.defaultHeaders;

        // authentication (bearer_auth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BundleServiceRequestR4>('get',`${this.basePath}/R4/ServiceRequest`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
